var course =[
    {
        "id": 1,
        "name": "The Web Developer Bootcamp",
        "description": "The only course you need to learn web development - HTML, CSS, JS, Node, and More!",
        "lecturer": "Colt Steele",
        "lecture": 406,
        "hours": 40,
        "image": "https://img-a.udemycdn.com/course/240x135/625204_436a_2.jpg",
        "price": 77,
    },
    {
        "id": 2,
        "name": "Machine Learning A-Z™: Hands-On Python & R In Data Science",
        "description": "Learn to create Machine Learning Algorithms in Python and R from two Data Science experts. Code templates included.",
        "lecturer": "Kirill Eremenko",
        "lecture": 40,
        "hours": 30,
        "image": "https://img-a.udemycdn.com/course/240x135/950390_270f_3.jpg",
        "price": 90,
    },
    {
        "id": 3,
        "name": "Angular - The Complete Guide (2020 Edition)",
        "description": 'Master Angular 10 (formerly "Angular 2") and build awesome, reactive web apps with the successor of Angular.js',
        "lecturer": "Maximilian Schwarzmüller",
        "lecture": 406,
        "hours": 90,
        "image": "https://img-a.udemycdn.com/course/240x135/756150_c033_2.jpg",
        "price": 50,
    },
    {
        "id": 4,
        "name": "The Complete JavaScript Course 2020: Build Real Projects!",
        "description": "The Complete JavaScript Course 2020: Build Real Projects!",
        "lecturer": "Jonas Schmedtmann",
        "lecture": 78,
        "hours": 70,
        "image": "https://img-a.udemycdn.com/course/240x135/851712_fc61_5.jpg",
        "price": 60,
    },
    {
        "id": 5,
        "name": "The Complete Web Developer Course 2.0",
        "description": "Learn Web Development by building 25 websites and mobile apps using HTML, CSS, Javascript, PHP, Python, MySQL & more!",
        "lecturer": "Rob Percival",
        "lecture": 30,
        "hours": 40,
        "image": "https://img-a.udemycdn.com/course/240x135/764164_de03_2.jpg",
        "price": 37,
    },
    {
        "id": 6,
        "name": "Modern React with Redux [2020 Update]",
        "description": "Master React v16.6.3 and Redux with React Router, Webpack, and Create-React-App.  Includes Hooks!",
        "lecturer": "Stephen Grider",
        "lecture": 13,
        "hours": 14,
        "image": "https://img-a.udemycdn.com/course/240x135/705264_caa9_11.jpg",
        "price": 150,
    },
    {
        "id": 7,
        "name": "Build Responsive Real World Websites with HTML5 and CSS3",
        "description": "The easiest way to learn modern web design, HTML5 and CSS3 step-by-step from scratch. Design AND code a huge project.",
        "lecturer": "Jonas Schmedtmann",
        "lecture": 25,
        "hours": 14,
        "image": "https://img-a.udemycdn.com/course/240x135/705264_caa9_11.jpg",
        "price": 80,
    },
    {
        "id": 8,
        "name": "Learn and Understand AngularJS",
        "description": "Master AngularJS and the Javascript concepts behind it, design custom directives, and build a single page application.",
        "lecturer": "Anthony Alicea",
        "lecture": 19,
        "hours": 17,
        "image": "https://img-a.udemycdn.com/course/240x135/289230_1056_16.jpg",
        "price": 55,
    },
    {
        "id": 9,
        "name": "Vue JS - The Complete Guide (incl. Vue Router & Vuex)",
        "description": "Vue.js is an awesome JavaScript Framework for building Frontend Applications! VueJS mixes the Best of Angular + React!",
        "lecturer": "Maximilian Schwarzmüller",
        "lecture": 65,
        "hours": 78,
        "image": "https://img-a.udemycdn.com/course/240x135/995016_ebf4.jpg",
        "price": 110,
    },
    {
        "id": 10,
        "name": "JavaScript Understanding the Weird Parts",
        "description": "An advanced JavaScript course for everyone! Scope, closures, prototypes, 'this', build your own framework, and more.",
        "lecturer": "Anthony Alicea",
        "lecture": 100,
        "hours": 12,
        "image": "https://img-a.udemycdn.com/course/240x135/364426_2991_5.jpg",
        "price": 250,
    },
    {
        "id": 11,
        "name": "Python and Django Full Stack Web Developer Bootcamp",
        "description": "Learn to build websites with HTML , CSS , Bootstrap , Javascript , jQuery , Python 3 , and Django!",
        "lecturer": "Jose Portilla",
        "lecture": 30,
        "hours": 15,
        "image": "https://img-a.udemycdn.com/course/240x135/822444_a6db.jpg",
        "price": 140,
    },
    {
        "id": 12,
        "name": "The Complete ASP.NET MVC 5 Course",
        "description": "Learn to build fast and secure web applications with ASP.NET MVC 5 - The most popular course with 40,000+ students!",
        "lecturer": "Mosh Hamedani",
        "lecture": 12,
        "hours": 23,
        "image": "https://img-a.udemycdn.com/course/240x135/806922_6310_3.jpg",
        "price": 51,
    },
    {
        "id": 13,
        "name": "Learn and Understand NodeJS",
        "description": "Dive deep under the hood of NodeJS. Learn V8, Express, the MEAN stack, core Javascript concepts, and more.",
        "lecturer": "Anthony Alicea",
        "lecture": 58,
        "hours": 7,
        "image": "https://img-a.udemycdn.com/course/240x135/461160_8d87_6.jpg",
        "price": 78,
    },
    {
        "id": 14,
        "name": "The Complete Angular Course: Beginner to Advanced",
        "description": "The most comprehensive Angular 4 (Angular 2+) course. Build a real e-commerce app with Angular, Firebase and Bootstrap 4",
        "lecturer": "Mosh Hamedani",
        "lecture": 47,
        "hours": 9,
        "image": "https://img-a.udemycdn.com/course/240x135/1247828_32bb.jpg",
        "price": 89,
    },
    {
        "id": 15,
        "name": "Modern JavaScript From The Beginning",
        "description": "Learn and build projects with pure JavaScript (No frameworks or libraries)",
        "lecturer": "Brad Traversy",
        "lecture": 14,
        "hours": 14,
        "image": "https://img-a.udemycdn.com/course/240x135/1463348_52a4_2.jpg",
        "price": 48,
    },
    {
        "id": 16,
        "name": "The Web Developer Bootcamp",
        "description": "The only course you need to learn web development - HTML, CSS, JS, Node, and More!",
        "lecturer": "Colt Steele",
        "lecture": 406,
        "hours": 40,
        "image": "https://img-a.udemycdn.com/course/240x135/625204_436a_2.jpg",
        "price": 77,
    }, {
        "id": 17,
        "name": "Machine Learning A-Z™: Hands-On Python & R In Data Science",
        "description": "Learn to create Machine Learning Algorithms in Python and R from two Data Science experts. Code templates included.",
        "lecturer": "Kirill Eremenko",
        "lecture": 40,
        "hours": 30,
        "image": "https://img-a.udemycdn.com/course/240x135/950390_270f_3.jpg",
        "price": 90,
    }, {
        "id": 18,
        "name": "Angular - The Complete Guide (2020 Edition)",
        "description": 'Master Angular 10 (formerly "Angular 2") and build awesome, reactive web apps with the successor of Angular.js',
        "lecturer": "Maximilian Schwarzmüller",
        "lecture": 406,
        "hours": 90,
        "image": "https://img-a.udemycdn.com/course/240x135/756150_c033_2.jpg",
        "price": 50,
    }, {
        "id": 19,
        "name": "The Complete JavaScript Course 2020: Build Real Projects!",
        "description": "The Complete JavaScript Course 2020: Build Real Projects!",
        "lecturer": "Jonas Schmedtmann",
        "lecture": 78,
        "hours": 70,
        "image": "https://img-a.udemycdn.com/course/240x135/851712_fc61_5.jpg",
        "price": 60,
    }, {
        "id": 20,
        "name": "The Complete Web Developer Course 2.0",
        "description": "Learn Web Development by building 25 websites and mobile apps using HTML, CSS, Javascript, PHP, Python, MySQL & more!",
        "lecturer": "Rob Percival",
        "lecture": 30,
        "hours": 40,
        "image": "https://img-a.udemycdn.com/course/240x135/764164_de03_2.jpg",
        "price": 37,
    }, {
        "id": 21,
        "name": "Modern React with Redux [2020 Update]",
        "description": "Master React v16.6.3 and Redux with React Router, Webpack, and Create-React-App.  Includes Hooks!",
        "lecturer": "Stephen Grider",
        "lecture": 13,
        "hours": 14,
        "image": "https://img-a.udemycdn.com/course/240x135/705264_caa9_11.jpg",
        "price": 150,
    }, {
        "id": 22,
        "name": "Build Responsive Real World Websites with HTML5 and CSS3",
        "description": "The easiest way to learn modern web design, HTML5 and CSS3 step-by-step from scratch. Design AND code a huge project.",
        "lecturer": "Jonas Schmedtmann",
        "lecture": 25,
        "hours": 14,
        "image": "https://img-a.udemycdn.com/course/240x135/705264_caa9_11.jpg",
        "price": 80,
    }, {
        "id": 23,
        "name": "Learn and Understand AngularJS",
        "description": "Master AngularJS and the Javascript concepts behind it, design custom directives, and build a single page application.",
        "lecturer": "Anthony Alicea",
        "lecture": 19,
        "hours": 17,
        "image": "https://img-a.udemycdn.com/course/240x135/289230_1056_16.jpg",
        "price": 55,
    }, {
        "id": 24,
        "name": "Vue JS - The Complete Guide (incl. Vue Router & Vuex)",
        "description": "Vue.js is an awesome JavaScript Framework for building Frontend Applications! VueJS mixes the Best of Angular + React!",
        "lecturer": "Maximilian Schwarzmüller",
        "lecture": 65,
        "hours": 78,
        "image": "https://img-a.udemycdn.com/course/240x135/995016_ebf4.jpg",
        "price": 110,
    }, {
        "id": 25,
        "name": "JavaScript Understanding the Weird Parts",
        "description": "An advanced JavaScript course for everyone! Scope, closures, prototypes, 'this', build your own framework, and more.",
        "lecturer": "Anthony Alicea",
        "lecture": 100,
        "hours": 12,
        "image": "https://img-a.udemycdn.com/course/240x135/364426_2991_5.jpg",
        "price": 250,
    }, {
        "id": 26,
        "name": "Python and Django Full Stack Web Developer Bootcamp",
        "description": "Learn to build websites with HTML , CSS , Bootstrap , Javascript , jQuery , Python 3 , and Django!",
        "lecturer": "Jose Portilla",
        "lecture": 30,
        "hours": 15,
        "image": "https://img-a.udemycdn.com/course/240x135/822444_a6db.jpg",
        "price": 140,
    }, {
        "id": 27,
        "name": "The Complete ASP.NET MVC 5 Course",
        "description": "Learn to build fast and secure web applications with ASP.NET MVC 5 - The most popular course with 40,000+ students!",
        "lecturer": "Mosh Hamedani",
        "lecture": 12,
        "hours": 23,
        "image": "https://img-a.udemycdn.com/course/240x135/806922_6310_3.jpg",
        "price": 51,
    }, {
        "id": 28,
        "name": "Learn and Understand NodeJS",
        "description": "Dive deep under the hood of NodeJS. Learn V8, Express, the MEAN stack, core Javascript concepts, and more.",
        "lecturer": "Anthony Alicea",
        "lecture": 58,
        "hours": 7,
        "image": "https://img-a.udemycdn.com/course/240x135/461160_8d87_6.jpg",
        "price": 78,
    }, {
        "id": 29,
        "name": "The Complete Angular Course: Beginner to Advanced",
        "description": "The most comprehensive Angular 4 (Angular 2+) course. Build a real e-commerce app with Angular, Firebase and Bootstrap 4",
        "lecturer": "Mosh Hamedani",
        "lecture": 47,
        "hours": 9,
        "image": "https://img-a.udemycdn.com/course/240x135/1247828_32bb.jpg",
        "price": 89,
    }, {
        "id": 30,
        "name": "Modern JavaScript From The Beginning",
        "description": "Learn and build projects with pure JavaScript (No frameworks or libraries)",
        "lecturer": "Brad Traversy",
        "lecture": 14,
        "hours": 14,
        "image": "https://img-a.udemycdn.com/course/240x135/1463348_52a4_2.jpg",
        "price": 48,
    }
]
export default course;