var course =[
    {
        "id": 1,
        "name": "The Web Developer Bootcamp",
        "description": "The only course you need to learn web development - HTML, CSS, JS, Node, and More!",
        "lecturer": "Colt Steele",
        "lecture": 406,
        "image": "https://img-a.udemycdn.com/course/240x135/625204_436a_2.jpg",
        "price": 50,
    },
    {
        "id": 2,
        "name": "Machine Learning A-Z™: Hands-On Python & R In Data Science",
        "description": "Learn to create Machine Learning Algorithms in Python and R from two Data Science experts. Code templates included.",
        "lecturer": "Kirill Eremenko",
        "lecture": 40,
        "image": "https://img-a.udemycdn.com/course/240x135/950390_270f_3.jpg",
        "price": 50,
    },
    {
        "id": 3,
        "name": "Angular - The Complete Guide (2020 Edition)",
        "description": 'Master Angular 10 (formerly "Angular 2") and build awesome, reactive web apps with the successor of Angular.js',
        "lecturer": "Maximilian Schwarzmüller",
        "lecture": 406,
        "image": "https://img-a.udemycdn.com/course/240x135/756150_c033_2.jpg",
        "price": 50,
    },
    {
        "id": 4,
        "name": "",
        "description": "",
        "lecturer": "",
        "lecture": 406,
        "image": "",
        "price": 50,
    },
    {
        "id": 5,
        "name": "",
        "description": "",
        "lecturer": "",
        "lecture": 406,
        "image": "",
        "price": 50,
    },
    {
        "id": 6,
        "name": "",
        "description": "",
        "lecturer": "",
        "lecture": 406,
        "image": "",
        "price": 50,
    },
    {
        "id": 7,
        "name": "",
        "description": "",
        "lecturer": "",
        "lecture": 406,
        "image": "",
        "price": 50,
    },
    {
        "id": 8,
        "name": "",
        "description": "",
        "lecturer": "",
        "lecture": 406,
        "image": "",
        "price": 50,
    },
    {
        "id": 9,
        "name": "",
        "description": "",
        "lecturer": "",
        "lecture": 406,
        "image": "",
        "price": 50,
    },
    {
        "id": 10,
        "name": "",
        "description": "",
        "lecturer": "",
        "lecture": 406,
        "image": "",
        "price": 50,
    },
    {
        "id": 11,
        "name": "",
        "description": "",
        "lecturer": "",
        "lecture": 406,
        "image": "",
        "price": 50,
    },
    {
        "id": 12,
        "name": "",
        "description": "",
        "lecturer": "",
        "lecture": 406,
        "image": "",
        "price": 50,
    },
    {
        "id": 13,
        "name": "",
        "description": "",
        "lecturer": "",
        "lecture": 406,
        "image": "",
        "price": 50,
    },
    {
        "id": 14,
        "name": "",
        "description": "",
        "lecturer": "",
        "lecture": 406,
        "image": "",
        "price": 50,
    },
    {
        "id": 15,
        "name": "",
        "description": "",
        "lecturer": "",
        "lecture": 406,
        "image": "",
        "price": 50,
    },
    {
        "id": 16,
        "name": "",
        "description": "",
        "lecturer": "",
        "lecture": 406,
        "image": "",
        "price": 50,
    },
    {
        "id": 17,
        "name": "",
        "description": "",
        "lecturer": "",
        "lecture": 406,
        "image": ""
    },
    {
        "id": 18,
        "name": "",
        "description": "",
        "lecturer": "",
        "lecture": 406,
        "image": "",
        "price": 50,
    },
    {
        "id": 19,
        "name": "",
        "description": "",
        "lecturer": "",
        "lecture": 406,
        "image": "",
        "price": 50,
    },
    {
        "id": 20,
        "name": "",
        "description": "",
        "lecturer": "",
        "lecture": 406,
        "image": "",
        "price": 50,
    },
    {
        "id": 21,
        "name": "",
        "description": "",
        "lecturer": "",
        "lecture": 406,
        "image": ""
    },
    {
        "id": 22,
        "name": "",
        "description": "",
        "lecturer": "",
        "lecture": 406,
        "image": "",
        "price": 50,
    },
    {
        "id": 23,
        "name": "",
        "description": "",
        "lecturer": "",
        "lecture": 406,
        "image": "",
        "price": 50,
    }
]
export default course;